//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Core.DataAccess.Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogentry
    {
        public Blogentry()
        {
            this.Comments = new HashSet<Comment>();
            this.Categories = new HashSet<Category>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
        public int CreatorID { get; set; }
        public string Lead { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
