//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Core.DataAccess.Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public System.Guid UNIQUE_ID { get; set; }
        public string SiteName { get; set; }
        public int NumberOfEntriesPerPage { get; set; }
        public string RegistrationMailSubject { get; set; }
        public string RegistrationMailBody { get; set; }
        public string RegistrationMailSender { get; set; }
        public string PasswordChangeMailSubject { get; set; }
        public string PasswordChangeMailBody { get; set; }
        public string PasswordChangeMailSender { get; set; }
        public string WelcomeMailSubject { get; set; }
        public string WelcomeMailBody { get; set; }
        public string WelcomeMailSender { get; set; }
        public string FooterText { get; set; }
        public string SmtpServerAddress { get; set; }
        public string SmtpServerUsername { get; set; }
        public string SmtpServerPassword { get; set; }
        public bool SmtpIsPasswordMandatoryForLogin { get; set; }
        public bool CommentsActivated { get; set; }
        public string Keywords { get; set; }
        public int SmtpServerPort { get; set; }
    }
}
