//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Core.DataAccess.Blog
{
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Blogentries = new HashSet<Blogentry>();
            this.Categories = new HashSet<Category>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserNameLowercase { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string EmailLowercase { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string Town { get; set; }
        public string ZIP { get; set; }
        public string LastName { get; set; }
        public string Forename { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public bool IsLocked { get; set; }
    
        public virtual ICollection<Blogentry> Blogentries { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
